config/routes.rb
Rails.application.routes.draw do
  get 'admin_area/users'
  resources :select_options
  resources :categories
  resources :roles
  resources :accounts do
    member do
      get 'area_chart_data'
      get 'donut_chart_data'
      get 'data_overview'
      get 'manage_categories'
    end
    collection do
      get 'my_accounts', as: "my_accounts"
    end
  end

  get 'accounts/:id/:start_date/:end_date', to: 'accounts#show'


  resources :work_times
  devise_for :users, path: "users"
  devise_for :companies, path: "companies"
  root 'static_pages#welcome'
  get 'static_pages/welcome'
  get 'static_pages/pricing', as: "pricing"


  #test
  if Rails.env.development?
    get 'test/generate_json_of_translation'
    get 'test/create_users'
    get 'test/create_accounts'
    get 'test/create_work_times'
    get 'test/destroy_all_users'
    get 'test/destroy_all_accounts'
    get 'test/destroy_all_work_times'
    get 'test/destroy_all_categories'
    get 'test/destroy_all_select_options'
    get 'test/create_select_options_only_json(/:name_of_file)', to: 'test#create_select_options_only_json'
    get 'test/create_categories_only_json(/:name_of_file)', to: 'test#create_categories_only_json'
    get 'test/create_work_times_only_json(/:name_of_file)', to: 'test#create_work_times_only_json'
    get 'test/create_users_only_json(/:name_of_file)', to: 'test#create_users_only_json'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/select_option.rb
class SelectOption < ApplicationRecord
  belongs_to :category
end

app/controllers/select_options_controller.rb
class SelectOptionsController < ApplicationController
  before_action :set_select_option, only: %i[ show edit update destroy ]
  after_action :verify_authorized

  # GET /select_options or /select_options.json
  def index
    authorize SelectOption
    @select_options = SelectOption.all
  end

  # GET /select_options/1 or /select_options/1.json
  def show
    authorize @select_option
  end

  # GET /select_options/new
  def new
    @select_option = SelectOption.new
    authorize @select_option
  end

  # GET /select_options/1/edit
  def edit
    authorize @select_option
  end

  # POST /select_options or /select_options.json
  def create
    @select_option = SelectOption.new(select_option_params)
    authorize @select_option

    respond_to do |format|
      if @select_option.save
        format.html { redirect_to manage_categories_account_path(@select_option.category.account), notice: "#{SelectOption.model_name.human} #{SelectOption.human_attribute_name("created_successfully")}" }
        format.json { render :show, status: :created, location: @select_option }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @select_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /select_options/1 or /select_options/1.json
  def update
    authorize @select_option
    respond_to do |format|
      if @select_option.update(select_option_params)
        format.html { redirect_to manage_categories_account_path(@select_option.category.account), notice: "#{SelectOption.model_name.human} #{SelectOption.human_attribute_name("updated_successfully")}" }
        format.json { render :show, status: :ok, location: @select_option }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @select_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /select_options/1 or /select_options/1.json
  def destroy
    authorize @select_option
    @select_option.destroy
    respond_to do |format|
      format.html { redirect_to manage_categories_account_path(@select_option.category.account), notice: "#{SelectOption.model_name.human} #{SelectOption.human_attribute_name("destroyed_successfully")}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_select_option
      @select_option = SelectOption.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def select_option_params
      params.require(:select_option).permit(:name, :category_id)
    end
end

app/helpers/select_options_helper.rb
module SelectOptionsHelper
end

app/views/select_options/_form.html.erb
<% category = select_option.category.present? ? select_option.category : category %>

<%= simple_form_for(select_option, html: { data: { cy: "select_option_form" }}) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: SelectOption.human_attribute_name("name_placeholder"), label: false %>
    <%= f.hidden_field :category_id, value: category.id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "primary-button" %>
  </div>
<% end %>

app/views/select_options/_table.html.erb
  <table class="table table-striped table-bordered mt-2">
    <thead>
      <tr>
        <th><%= SelectOption.model_name.human(count: 2) %></th>
        <th><%= t("actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% category.select_options.each do |select_option|  %>
        <tr>
          <td>
            <%= select_option.name %>
          </td>
          <td>
            <div class="d-grid gap-0">
              <%= link_to edit_select_option_path(select_option), class: "action_button", data: { cy: "edit_select_option" } do %>
              <i class="bi bi-pencil-square"></i> <%= t("edit") %>
            <% end %>
              <br>
              <%= link_to select_option, method: :delete, data: { confirm: 'Are you sure?', cy: "delete_select_option" }, class: "action_delete_button" do %>
                <i class="bi bi-x-square"></i> <%= t("delete") %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
      <tr>
        <td>
          <strong>
            <%= SelectOption.human_attribute_name("enter", select_option: SelectOption.model_name.human) %>
          </strong>
          <%= render 'select_options/form', select_option: SelectOption.new, category: category %>
        <td>
      </tr>
    </tbody>
  </table>

app/views/select_options/edit.html.erb
<div class="container">
  <h1><%= SelectOption.human_attribute_name("edit", select_option: SelectOption.model_name.human) %></h1>
  <%= render 'form', select_option: @select_option %>
</div>

app/views/select_options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Select Options</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @select_options.each do |select_option| %>
      <tr>
        <td><%= select_option.name %></td>
        <td><%= link_to 'Show', select_option %></td>
        <td><%= link_to 'Edit', edit_select_option_path(select_option) %></td>
        <td><%= link_to 'Destroy', select_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Select Option', new_select_option_path %>

app/views/select_options/new.html.erb
<h1>New Select Option</h1>

<%= render 'form', select_option: @select_option %>

<%= link_to 'Back', select_options_path %>

app/views/select_options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @select_option.name %>
</p>

<%= link_to 'Edit', edit_select_option_path(@select_option) %> |
<%= link_to 'Back', select_options_path %>