config/routes.rb
Rails.application.routes.draw do
  get 'admin_area/users'
  resources :select_options
  resources :categories
  resources :roles
  resources :accounts do
    member do
      get 'area_chart_data'
      get 'donut_chart_data'
      get 'data_overview'
      get 'manage_categories'
    end
    collection do
      get 'my_accounts', as: "my_accounts"
    end
  end

  get 'accounts/:id/:start_date/:end_date', to: 'accounts#show'


  resources :work_times
  devise_for :users, path: "users"
  devise_for :companies, path: "companies"
  root 'static_pages#welcome'
  get 'static_pages/welcome'
  get 'static_pages/pricing', as: "pricing"


  #test
  if Rails.env.development?
    get 'test/generate_json_of_translation'
    get 'test/create_users'
    get 'test/create_accounts'
    get 'test/create_work_times'
    get 'test/destroy_all_users'
    get 'test/destroy_all_accounts'
    get 'test/destroy_all_work_times'
    get 'test/destroy_all_categories'
    get 'test/destroy_all_select_options'
    get 'test/create_select_options_only_json(/:name_of_file)', to: 'test#create_select_options_only_json'
    get 'test/create_categories_only_json(/:name_of_file)', to: 'test#create_categories_only_json'
    get 'test/create_work_times_only_json(/:name_of_file)', to: 'test#create_work_times_only_json'
    get 'test/create_users_only_json(/:name_of_file)', to: 'test#create_users_only_json'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/work_time.rb
class WorkTime < ApplicationRecord
  belongs_to :account

  validates :task, presence: true
  validates :minutes, numericality: true, presence: true

  def self.in_hours(minutes)
    "#{(minutes/60).to_i} h #{(minutes % 60).round(0)} min"
  end
end

app/controllers/work_times_controller.rb
class WorkTimesController < ApplicationController
  before_action :set_work_time, only: %i[ show edit update destroy ]
  after_action :verify_authorized
  #after_action :verify_authorized

  # GET /work_times or /work_times.json
  def index
    authorize WorkTime
    @work_times = WorkTime.all
  end

  # GET /work_times/1 or /work_times/1.json
  def show
    authorize @work_time
  end

  # GET /work_times/new
  def new
    @work_time = WorkTime.new
    authorize @work_time
  end

  # GET /work_times/1/edit
  def edit
    authorize @work_time
  end

  # POST /work_times or /work_times.json
  def create
    @work_time = WorkTime.new(work_time_params)
    authorize @work_time

    respond_to do |format|
      if @work_time.save
        format.html { redirect_to account_path(@work_time.account), notice: "#{WorkTime.model_name.human} #{WorkTime.human_attribute_name("work_time_created_successfully")}" }
        format.json { render :show, status: :created, location: @work_time }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_times/1 or /work_times/1.json
  def update
    authorize @work_time
    respond_to do |format|
      if @work_time.update(work_time_params)
        format.html { redirect_to account_path(@work_time.account), notice: "#{WorkTime.model_name.human} #{WorkTime.human_attribute_name("work_time_updated_successfully")}" }
        format.json { render :show, status: :ok, location: @work_time }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_times/1 or /work_times/1.json
  def destroy
    authorize @work_time
    @work_time.destroy
    account = @work_time.account
    respond_to do |format|
      format.html { redirect_to account_path(account), notice: "#{WorkTime.model_name.human} #{WorkTime.human_attribute_name("work_time_destroyed_successfully")}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_time
      @work_time = WorkTime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_time_params
      params.require(:work_time).permit(:task, :minutes, :datetime, :account_id, :categories => {})
    end
end

app/helpers/work_times_helper.rb
module WorkTimesHelper
end

app/views/work_times/_area_chart.html.erb
<% area_chart_data_interval = cookies[:area_chart_data_interval].blank? ? "P1W" : cookies[:area_chart_data_interval] %>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link select-interval-element <%= "active" if area_chart_data_interval == "P1D" %>" data-interval="P1D" aria-current="page"><%= t("day-interval") %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link select-interval-element <%= "active" if area_chart_data_interval == "P1W" %>" data-interval="P1W"><%= t("week-interval") %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link select-interval-element <%= "active" if area_chart_data_interval == "P1M" %>" data-interval="P1M"><%= t("month-interval") %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link select-interval-element <%= "active" if area_chart_data_interval == "P1Y" %>"  data-interval="P1Y"><%= t("year-interval") %></a>
    </li>
  </ul>

  <div id="diagram">
    <div class="text-center">
      <div class="spinner-border" style="width: 3rem; height: 3rem;" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
  </div>



<script type="text/javascript">

  var account = <%= raw @account.to_json %>;
  var interval = "<%= cookies[:area_chart_data_interval].blank? ? "P1W" : cookies[:area_chart_data_interval] %>";
  var cachedWidth = $( window ).width();

  var spinner_html = `
  <div class="text-center my-4" style="height: 500px">
    <div class="spinner-grow" style="width: 3rem; height: 3rem;" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
`;


  $(document).ready(function() {

    $( ".select_date_range_button" ).click(function() {

    });

    $( function() {
      $( "#work_time_start_date" ).datepicker({'language' : 'de', 'dateFormat' : 'dd-mm-yy', firstDay: 1 });
      $( "#work_time_end_date" ).datepicker({'language' : 'de', 'dateFormat' : 'dd-mm-yy', firstDay: 1 });
    } );

    var cachedWidth = $(window).width();

    //AreaChart2();
    getDataAndDraw("#diagram", interval);

  });

  //event-watchers
  $( ".select-interval-element" ).click(function() {
    $(".select-interval-element").removeClass("active");
    interval = this.getAttribute('data-interval');
    $(this).addClass("active");
    getDataAndDraw("#diagram", interval);
  });

  $( window ).resize(function() {
    var newWidth = $( window ).width();
    if(newWidth !== cachedWidth){
      //console.log("resize!");
      cachedWidth = newWidth;
      width = newWidth;
      getDataAndDraw('#diagram', interval);

    }
  });



  //functions
  function getDataAndDraw(container, interval){
    $(container).empty();
    $(container).html(spinner_html);

    $.ajax({
      url: "<%= area_chart_data_account_path(account) %>",
      method: 'GET',
      data: {
        id: account.id,
        interval: interval,
        start_date: "<%= start_date.strftime("%d-%m-%Y") %>",
        end_date: "<%= end_date.strftime("%d-%m-%Y") %>"
      }
    }).always(function( data ) {
      $(container).empty();
      //draw(container, data);
      AreaChart2(container, data);
    });
  }

  function AreaChart2(container, data_original) {

    data = []

    for (var i = 0; i < data_original.length; i++) {
      data.push(
          {
            date: d3.timeParse("%Y-%m-%d")(data_original[i].date),
            value : data_original[i].minutes,
            interval: data_original[i].interval
          }
      )
    }


    // set the dimensions and margins of the graph
    var margin = {top: 50, right: 50, bottom: 50, left: 50},
          width = $(container).width() - margin.left - margin.right,
          height = 500 - margin.top - margin.bottom;

    // append the svg object to the body of the page
    var svg = d3.select(container)
      .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
      .append("g")
        .attr("transform",`translate(${margin.left},${margin.top})`);

        // Add X axis --> it is a date format
        var x = d3.scaleTime()
          .domain(d3.extent(data, d => d.date))
          .range([ 0, width ]);
          svg.append("g")
            .attr("transform", `translate(0,${height})`)
            .call(d3.axisBottom(x));

        // Add Y axis
        var y = d3.scaleLinear()
          .domain([0, d3.max(data, d => +d.value)])
          .range([ height, 0 ]);
          svg.append("g")
            .call(d3.axisLeft(y));

        // Add the area
        svg.append("path")
          .datum(data)
          .attr("class", "area-chart-bg-d-color")
          //.attr("fill", "#cce5df")
          .attr("stroke", "#69b3a2")
          .attr("stroke-width", 1.5)
          .attr("d", d3.area()
            .x(d => x(d.date))
            .y0(y(0))
            .y1(d => y(d.value))
              )

      // Add the line
      svg.append("path")
        .datum(data)
        .attr("fill", "none")
        .attr("class", "area-chart-line-g-color")
        //.attr("stroke", "#69b3a2")
        .attr("stroke-width", 4)
        .attr("d", d3.line()
          .x(d => x(d.date))
          .y(d => y(d.value))
          )

      // Add the circles
      svg.selectAll("myCircles")
        .data(data)
        .join("circle")
          //.attr("fill", "blue")
          .attr("stroke", "none")
          .attr("minutes", d => d.value)
          .attr("interval", d => d.interval)
          .attr("date", d => d.date)
          .attr("cx", d => x(d.date))
          .attr("cy", d => y(d.value))
          .attr("r", 6)
          .attr("class", "tooltippable area-chart-bg-a-color");

// create a tooltip
var tooltip = d3.select(container)
  .append("div")
  .style("opacity", 0)
  .attr("class", "tooltip")
  .style("background-color", "white")
  .style("border", "solid")
  .style("border-width", "2px")
  .style("border-radius", "5px")
  .style("padding", "5px")

//
d3.selectAll(".tooltippable")
  .on("mouseover", function(){
     tooltip
    .style("visibility", "visible")
    .style("opacity", 1)
    ;})
  .on("mousemove", function(){
    d3.select(this)
    .attr("r", 8);

     tooltip
    .style("top", (event.pageY)+"px")
    .style("left",(event.pageX)+"px")
    .html(d3.select(this).attr("interval") + " <br /> " + d3.select(this).attr("minutes"))
    ;})
  .on("mouseout", function(){
    d3.select(this)
    .attr("r", 5);

     tooltip
    .style("visibility", "hidden")
    .style("opacity", 0)
    ;});

      }

  function AreaChart(data, {
    x = ([x]) => x, // given d in data, returns the (temporal) x-value
    y = ([, y]) => y, // given d in data, returns the (quantitative) y-value
    defined, // given d in data, returns true if defined (for gaps)
    curve = d3.curveLinear, // method of interpolation between points
    marginTop = 20, // top margin, in pixels
    marginRight = 30, // right margin, in pixels
    marginBottom = 30, // bottom margin, in pixels
    marginLeft = 40, // left margin, in pixels
    width = 640, // outer width, in pixels
    height = 400, // outer height, in pixels
    xType = d3.scaleUtc, // type of x-scale
    xDomain, // [xmin, xmax]
    xRange = [marginLeft, width - marginRight], // [left, right]
    yType = d3.scaleLinear, // type of y-scale
    yDomain, // [ymin, ymax]
    yRange = [height - marginBottom, marginTop], // [bottom, top]
    yFormat, // a format specifier string for the y-axis
    yLabel, // a label for the y-axis
    color = "currentColor" // fill color of area
  } = {}) {
    // Compute values.
    var X = d3.map(data, x);
    var Y = d3.map(data, y);
    var I = d3.range(X.length);

    // Compute which data points are considered defined.
    if (defined === undefined) defined = (d, i) => !isNaN(X[i]) && !isNaN(Y[i]);
    var D = d3.map(data, defined);

    // Compute default domains.
    if (xDomain === undefined) xDomain = d3.extent(X);
    if (yDomain === undefined) yDomain = [0, d3.max(Y) + d3.max(Y) / 5];

    // varruct scales and axes.
    var xScale = xType(xDomain, xRange);
    var yScale = yType(yDomain, yRange);
    var xAxis = d3.axisBottom(xScale).ticks(width / 80);
    var yAxis = d3.axisLeft(yScale).ticks(height / 40, yFormat);

    // varruct an area generator.
    var area = d3.area()
        .defined(i => D[i])
        .curve(curve)
        .x(i => xScale(X[i]))
        .y0(yScale(0))
        .y1(i => yScale(Y[i]));

    var svg = d3.select(container).append('svg')
        .attr("width", width)
        .attr("height", height)
        .attr("viewBox", [0, 0, width, height])
        .attr("style", "max-width: 100%; height: auto; height: intrinsic;");

    svg.append("g")
        .attr("transform", `translate(${marginLeft},0)`)
        .call(yAxis)
        .call(g => g.select(".domain").remove())
        .call(g => g.selectAll(".tick line").clone()
            .attr("x2", width - marginLeft - marginRight)
            .attr("stroke-opacity", 0.1))
        .call(g => g.append("text")
            .attr("x", -marginLeft)
            .attr("y", 10)
            .attr("fill", "currentColor")
            .attr("text-anchor", "start")
            .text(yLabel));

    svg.append("path")
        .attr("fill", color)
        .attr("d", area(I));

    //svg.append("g")
    //    .attr("transform", `translate(0,${height - marginBottom})`)
    //    .call(xAxis);


    // Create the scale
    var x = d3.scaleBand()
        .domain(d3.extent(X))       // This is what is written on the Axis: from 0 to 100
        .range(xRange) ;                      // This is where the axis is placed: from 100 px to 800px
      //  .padding([0])                          // Goes between 0 and 1. Default is 0

    // Draw the axis
    svg
      .append("g")
      .attr("transform", `translate(0,${height - marginBottom})`)      // This controls the vertical position of the Axis
      .call(d3.axisBottom(x));

    return svg.node();
  }

</script>

app/views/work_times/_donut_chart.html.erb
  <h3><%= category.name %></h3>
  <div class="donut_chart <%= "donut_chart_category-#{category.id}" %>">
    <div class="text-center">
      <div class="spinner-border" style="width: 3rem; height: 3rem;" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
  </div>



<script type="text/javascript">

  var start_date = "<%= start_date.strftime("%d-%m-%Y") %>";
  var end_date = "<%= end_date.strftime("%d-%m-%Y") %>";
  var category = "<%= category.name %>";
  var container = ".<%= "donut_chart_category-#{category.id}" %>";

  getDataAndDrawDonutChart(container);

  //functions
  function getDataAndDrawDonutChart(container){
    $(container).empty();
    $(container).html(spinner_html);

    $.ajax({
      url: "<%= donut_chart_data_account_path(account) %>",
      method: 'GET',
      data: {
        id: account.id,
        start_date: start_date,
        end_date: end_date,
        category: category
      }
    }).always(function( data ) {
      $(container).empty();
      //draw(container, data);
      DonutChart(container, data[0]);
    });
  }

  function DonutChart(container, data){
    // set the dimensions and margins of the graph

    var width = $(container).width(),
        height = 500,
        margin = 40;

    // The radius of the pieplot is half the width or half the height (smallest one). I subtract a bit of margin.
    var radius = Math.min(width, height) / 2 - margin

    // append the svg object to the div called 'my_dataviz'
    var svg = d3.select(container)
      .append("svg")
        .attr("width", width)
        .attr("height", height)
      .append("g")
        .attr("transform", `translate(${width/2},${height/2})`);

    // Create dummy data
    //var data = {a: 9, b: 20, c:30, d:8, e:12, f:3, g:7, h:14}

    // set the color scale
    var data_keys = Object.keys(data);
    var color = d3.scaleOrdinal().domain(data_keys).range(d3.schemeDark2);
    //var color = d3.scaleSequential().domain(data_keys).interpolator(d3.interpolateViridis);

    // Compute the position of each group on the pie:
    var pie = d3.pie()
      .sort(null) // Do not sort group by size
      .value(d => d[1])
    var data_ready = pie(Object.entries(data))

    // The arc generator
    var arc = d3.arc()
      .innerRadius(radius * 0.5)         // This is the size of the donut hole
      .outerRadius(radius * 0.8)

    // Another arc that won't be drawn. Just for labels positioning
    var outerArc = d3.arc()
      .innerRadius(radius * 0.9)
      .outerRadius(radius * 0.9)

    // Build the pie chart: Basically, each part of the pie is a path that we build using the arc function.
    svg
      .selectAll('allSlices')
      .data(data_ready)
      .join('path')
      .attr('d', arc)
      .attr('fill', d => color(d.index % data_keys.length))
      .attr("stroke", "white")
      .style("stroke-width", "2px")
      .style("opacity", 0.7)

    // Add the polylines between chart and labels:
    svg
      .selectAll('allPolylines')
      .data(data_ready)
      .join('polyline')
        .attr("stroke", "black")
        .style("fill", "none")
        .attr("stroke-width", 1)
        .attr('points', function(d) {
          var posA = arc.centroid(d) // line insertion in the slice
          var posB = outerArc.centroid(d) // line break: we use the other arc generator that has been built only for that
          var posC = outerArc.centroid(d); // Label position = almost the same as posB
          var midangle = d.startAngle + (d.endAngle - d.startAngle) / 2 // we need the angle to see if the X position will be at the extreme right or extreme left
          posC[0] = radius * 0.95 * (midangle < Math.PI ? 1 : -1); // multiply by 1 or -1 to put it on the right or on the left
          return [posA, posB, posC]
        })

    // Add the polylines between chart and labels:
    svg
      .selectAll('allLabels')
      .data(data_ready)
      .join('text')
        .text(d => d.data[0])
        .attr('transform', function(d) {
            var pos = outerArc.centroid(d);
            var midangle = d.startAngle + (d.endAngle - d.startAngle) / 2
            pos[0] = radius * 0.99 * (midangle < Math.PI ? 1 : -1);
            return `translate(${pos})`;
        })
        .style('text-anchor', function(d) {
            var midangle = d.startAngle + (d.endAngle - d.startAngle) / 2
            return (midangle < Math.PI ? 'start' : 'end')
        })
        //end of DonutChart
  }


  </script>

app/views/work_times/_form.html.erb
<% account = work_time.account.present? ? work_time.account : account %>

<%= simple_form_for(work_time, html: { data: { cy: "work_time_form" }}) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :task, placeholder: WorkTime.human_attribute_name("task_placeholder") %>
    <%= f.input :minutes, placeholder: WorkTime.human_attribute_name("minutes_placeholder") %>
    <%= f.input :datetime, discard_hour: true %>

    <p class="mt-2 mb-0">
      <strong><%= Category.model_name.human(count: 2) %> </strong>
    </p>
    <div class="information_box">
      <div class="row">
        <div class="col-2 col-md-1 d-flex flex-column justify-content-center align-items-center">
          <i class="bi bi-info-circle" style="font-size: 1.8em"></i>
        </div>
        <div class="col-10 col-md-11">
          <%= Category.human_attribute_name("information_about_categories") %>
         <br>
         <%= link_to t("manage_categories"), manage_categories_account_path(account), data: { cy: "manage_categories" } %>
        </div>
      </div>
    </div>

    <%= f.simple_fields_for :categories do |category_form| %>
      <% account.categories.each do |category| %>
        <%#= category_form.input category.name, :input_html => { :value => work_time.categories[category.name] }, required: false %>
        <%= category_form.input category.name, collection: category.select_options.pluck(:name), selected: work_time.categories[category.name], prompt: I18n.t("select_category", category: category.name), include_blank: true, required: false, input_html: { data: {input_name: category.name} } %>
      <% end %>
    <% end %>

    <%= f.hidden_field :account_id, value: account.id %>
  </div>

  <div class="form-actions mt-2">
    <%= f.button :submit, class: "primary-button" %>
  </div>
<% end %>

app/views/work_times/_table.html.erb
  <table class="table table-striped table-bordered table-responsive">
    <thead>
      <tr>
        <th scope="col"><%= WorkTime.human_attribute_name("created_at") %></th>
        <th scope="col"><%= WorkTime.human_attribute_name("task") %></th>
        <th scope="col"><%= WorkTime.human_attribute_name("time") %></th>
        <th scope="col"><%= WorkTime.human_attribute_name("time_in_minutes") %></th>
        <% account.categories.each do |category| %>
          <th scope="col"><%= category.name %></th>
        <% end %>
        <th scope="col"><%= t("actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% earliest_work_time = start_date.blank? ? WorkTime.order(:datetime).first.datetime : start_date %>
      <% latest_work_time = end_date.blank? ? WorkTime.order(:datetime).last.datetime : end_date %>
      <% WorkTime.where(account_id: account.id).where(datetime: earliest_work_time..latest_work_time).order(:datetime).reverse_order.each do |work_time| %>
      <tr>
        <td><%= l(work_time.datetime, format: :short) %></td>
        <td><%= work_time.task %></td>
        <td><%= WorkTime.in_hours(work_time.minutes) %></td>
        <td><%= work_time.minutes %></td>
        <% account.categories.each do |category| %>
          <td data-category="<%= category.name %>"><%= work_time.categories[category.name] unless work_time.categories[category.name].blank? %></td>
        <% end %>
        <td>
        <div class="d-grid gap-0">
          <%= link_to edit_work_time_path(work_time), class: "action_button", data: { cy: "edit_work_time" } do %>
            <i class="bi bi-pencil-square"></i> <%= t("edit") %>
          <% end %>
            <br>
          <%= link_to work_time, method: :delete, data: { confirm: 'Are you sure?', cy: "delete_work_time" }, class: "action_delete_button" do %>
              <i class="bi bi-x-square"></i> <%= t("delete") %>
          <% end %>
          </div>
        </td>
      </tr>
      <% end %>
      <tr class="table-secondary">
        <td>Total </td>
        <td><%= WorkTime.where(account_id: account.id).where(datetime: earliest_work_time..latest_work_time).count %> <%= WorkTime.human_attribute_name("tasks") %></td>
        <% sum_of_all_minutes = WorkTime.where(account_id: account.id).where(datetime: earliest_work_time..latest_work_time).sum(:minutes) %>
        <td>
          <%= WorkTime.in_hours(sum_of_all_minutes) %>
        </td>
        <td>
          <%= sum_of_all_minutes %>
        </td>
        <% account.categories.each do |category| %>
          <td></td>
        <% end %>
        <td>
        </td>
      </tr>
    </tbody>
  </table>

app/views/work_times/edit.html.erb
<main class="container main_left">
<h1><%= WorkTime.human_attribute_name("edit", work_time: WorkTime.model_name.human) %></h1>

<%= render 'form', work_time: @work_time %>

<%= link_to t("back"), account_path(@work_time.account), class: "secondary-button" %>
</main>

app/views/work_times/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Work Times</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Minutes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_times.each do |work_time| %>
      <tr>
        <td><%= work_time.task %></td>
        <td><%= work_time.minutes %></td>
        <td><%= link_to 'Show', work_time %></td>
        <td><%= link_to 'Edit', edit_work_time_path(work_time) %></td>
        <td><%= link_to 'Destroy', work_time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work Time', new_work_time_path %>

app/views/work_times/new.html.erb
<div class="container">
  <h1>New Work Time</h1>

  <%= render 'form', work_time: @work_time %>

  <%= link_to t("go_back"), work_times_path, class: "secondary-button" %>
</div>

app/views/work_times/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @work_time.task %>
</p>

<p>
  <strong>Minutes:</strong>
  <%= @work_time.minutes %>
</p>

<%= link_to 'Edit', edit_work_time_path(@work_time) %> |
<%= link_to 'Back', work_times_path %>