config/routes.rb
Rails.application.routes.draw do
  get 'admin_area/users'
  resources :select_options
  resources :categories
  resources :roles
  resources :accounts do
    member do
      get 'area_chart_data'
      get 'donut_chart_data'
      get 'data_overview'
      get 'manage_categories'
    end
    collection do
      get 'my_accounts', as: "my_accounts"
    end
  end

  get 'accounts/:id/:start_date/:end_date', to: 'accounts#show'


  resources :work_times
  devise_for :users, path: "users"
  devise_for :companies, path: "companies"
  root 'static_pages#welcome'
  get 'static_pages/welcome'
  get 'static_pages/pricing', as: "pricing"


  #test
  if Rails.env.development?
    get 'test/generate_json_of_translation'
    get 'test/create_users'
    get 'test/create_accounts'
    get 'test/create_work_times'
    get 'test/destroy_all_users'
    get 'test/destroy_all_accounts'
    get 'test/destroy_all_work_times'
    get 'test/destroy_all_categories'
    get 'test/destroy_all_select_options'
    get 'test/create_select_options_only_json(/:name_of_file)', to: 'test#create_select_options_only_json'
    get 'test/create_categories_only_json(/:name_of_file)', to: 'test#create_categories_only_json'
    get 'test/create_work_times_only_json(/:name_of_file)', to: 'test#create_work_times_only_json'
    get 'test/create_users_only_json(/:name_of_file)', to: 'test#create_users_only_json'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  belongs_to :company, optional: true
  has_many :work_times
  has_many :categories

  def self.calculate_work_load_in_duration(work_load, start_date, end_date)
    work_load*((end_date - start_date).to_f / 7)
  end

  def area_chart_data(start_date: nil, end_date: nil, interval: nil)

    return [{date: Date.today.to_s, minutes: 0}] if self.work_times.empty?

    if interval.blank?
      interval = 1.day
    else
      interval = ActiveSupport::Duration.parse(interval)
    end

    if start_date.nil?
      start_date = self.work_times.order(:datetime).limit(1).first.datetime.to_date
    else
      start_date = DateTime.parse(start_date)
    end

    if end_date.nil?
      end_date = self.work_times.order(:datetime).reverse_order.limit(1).first.datetime.to_date
    else
      end_date = DateTime.parse(end_date)
    end


    data_array = []

    while (start_date === end_date) || (start_date.before?(end_date))

    sum_of_minutes = self.work_times.where(datetime: start_date..start_date + interval - 1.day).sum(:minutes)
    data_array.push(
      {
        date: start_date.to_date.to_s,
        minutes: sum_of_minutes,
        interval: "<strong>#{start_date.to_s} - #{(start_date + interval - 1.day).to_s}</strong>"
      }
    )
    start_date = start_date + interval

    # while loop ends here
    end


    #self.work_times.each do |work_time|
    #  data_array.push({date: work_time.datetime.to_date.to_s, minutes: work_time.minutes})
    #end

    data_array

    #data_array.as_json.to_json

    #self.work_times.group_by_week(:datetime).sum(:minutes).to_jsonself.work_times.group_by_week(:datetime).sum(:minutes).to_json unless self.work_times.empty? || self.work_times.count == 1
    #[{"date": "01-01-2021", "minutes": 200}, {"date": "2019-02-03", "minutes": 100}].to_json
  end

  def donut_chart_data(start_date: nil, end_date: nil, category: nil)

    #{a: 9, b: 20, c:30, d:8, e:12, f:3, g:7, h:14}

    #return [{a: 9, b: 20, c:30, d:8, e:12, f:3, g:7, h:14}]

    return [{leer: 100}] if self.work_times.empty?

    if start_date.nil?
      start_date = self.work_times.order(:datetime).limit(1).first.datetime.to_date
    else
      start_date = DateTime.parse(start_date)
    end

    if end_date.nil?
      end_date = self.work_times.order(:datetime).reverse_order.limit(1).first.datetime.to_date
    else
      end_date = DateTime.parse(end_date)
    end


    data_array = []
    hash_with_values_for_donut_chart = {}


      #distinct_values = create_array_with_distinct_values_of_a_category(category.name, self.work_times.where("(categories->'#{category.name}') is not null").where(datetime: start_date..end_date))
      distinct_values = create_array_with_distinct_values_of_a_category(category, self.work_times.where(datetime: start_date..end_date))

      distinct_values.uniq!

      total_minutes = self.work_times.where(datetime: start_date..end_date).sum(:minutes)

      distinct_values.each do |value|

        if value.blank?
          null_minutes = self.work_times.where.not("(categories->'#{category}') is not null").where(datetime: start_date..end_date).sum(:minutes)
          empty_minutes = self.work_times.where('categories @> ?', {"#{category}": ""}.to_json).where(datetime: start_date..end_date).sum(:minutes)
          minutes = null_minutes + empty_minutes
          hash_with_values_for_donut_chart["#{I18n.t("empty")} - #{calculate_percentage(total_minutes, minutes)}%"] = minutes
        else
          minutes = self.work_times.where('categories @> ?', {"#{category}": "#{value}"}.to_json).where(datetime: start_date..end_date).sum(:minutes)
          hash_with_values_for_donut_chart["#{value} - #{calculate_percentage(total_minutes, minutes)}%"] = minutes
        end
      end

    #WorkTime.all.select("categories -> 'Projekt'")
    #UserActivity.pluck("raw_data->'activity'->'type'")
    [hash_with_values_for_donut_chart]
  end

  after_create :add_category_project_to_account

  private

  def calculate_percentage(total_value, part_value)
    percentage = (part_value.to_f/total_value.to_f)*100

    (percentage).round(1)
  end

  def add_category_project_to_account
    category = Category.create(account_id: self.id, name: I18n.t("area"))
    SelectOption.create(name: I18n.t("project1"), category_id: category.id)
    SelectOption.create(name: I18n.t("project2"), category_id: category.id)
    SelectOption.create(name: I18n.t("project3"), category_id: category.id)
    SelectOption.create(name: I18n.t("customer_care"), category_id: category.id)
    SelectOption.create(name: I18n.t("administration"), category_id: category.id)
    SelectOption.create(name: I18n.t("social_media"), category_id: category.id)
    SelectOption.create(name: I18n.t("workshops"), category_id: category.id)
    SelectOption.create(name: I18n.t("miscellaneous"), category_id: category.id)
  end

  def create_hash_with_distinct_values_of_a_category(category, records)
    distinct_values = {}

    records.each do |record|
      distinct_values[category] = record["categories"][category]
    end
    distinct_values
  end

  def create_array_with_distinct_values_of_a_category(category, records)
    distinct_values = []

    records.each do |record|
      distinct_values.push(record["categories"][category])
    end
    distinct_values
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy area_chart_data donut_chart_data data_overview manage_categories]
  before_action :set_start_and_end_date, only: %i[show data_overview]
  after_action :verify_authorized


  def my_accounts
    #if params[:user_id].present?
    #  @user = User.find(params[:user_id])
    #else
    #  @user = current_user
    #end

    @user = current_user
    authorize Account
  end

  def manage_categories
    authorize @account
  end

  # GET /accounts or /accounts.json
  def index
    authorize Account
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
    authorize @account
  end

  # GET /accounts/new
  def new
    @account = Account.new
    authorize @account
  end

  # GET /accounts/1/edit
  def edit
    authorize @account
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)
    authorize @account

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    authorize @account
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    authorize @account
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def data_overview
    authorize @account
    render layout: false
  end

  def area_chart_data
    authorize @account
    cookies[:area_chart_data_interval] = params[:interval]
    render json: @account.area_chart_data(
      interval: params[:interval],
      start_date: params[:start_date],
      end_date: params[:end_date]
    ).to_json
  end

  def donut_chart_data
    authorize @account
    render json: @account.donut_chart_data(
      start_date: params[:start_date],
      end_date: params[:end_date],
      category: params[:category]
    ).to_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    def set_start_and_end_date
      if params[:start_date].present?
        @start_date = DateTime.parse(params[:start_date])
      elsif !@account.work_times.empty?
        @start_date = @account.work_times.order(:datetime).first.datetime
      else
        @start_date = DateTime.now
      end

      if params[:end_date].present?
        @end_date = DateTime.parse(params[:end_date])
      elsif !@account.work_times.empty?
        @end_date = @account.work_times.order(:datetime).last.datetime
      else
        @end_date = DateTime.now
      end
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :text, :work_load_per_week, :user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_data_overview.html.erb
<div class="standard-card data_overview" style="min-height: 100vh">
  <div class="card-body">
    <h5 class="card-title"><%= t("overview") %></h5>
    <p>
      <%= l(start_date, format: :date_range) %> - <%= l(end_date, format: :date_range) %>
    </p>
    <%= render "accounts/select_date_range", account: account, start_date: start_date, end_date: end_date %>
    <%= render "work_times/table", account: account, start_date: start_date, end_date: end_date %>
    <%= render "work_times/area_chart", account: account, start_date: start_date, end_date: end_date %>
    <% account.categories.each do |category| %>
      <%= render "work_times/donut_chart", account: account, start_date: start_date, end_date: end_date, category: category %>
    <% end %>

  </div>
</div>

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :work_load_per_week %>

    <% user = user.blank? ? current_user : user.id %>
    <%= f.hidden_field :user_id, value: user.id %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "primary-button" %>
  </div>
<% end %>

app/views/accounts/_information_card.html.erb
<div class="standard-card ">
  <div class="card-body">
    <h5 class="card-title"><%= account.name %></h5>
    <div class="row">
      <div class="col-12 col-sm-6">
        <p class="card-text">
          <%= t("today") %>: <%= WorkTime.in_hours(account.work_times.where(datetime: Date.today..Date.today + 1.day).sum(:minutes)) %> / <%= WorkTime.in_hours(account.work_load_per_week/7) %>
          <br />
          <%= t("this_week") %>: <%= WorkTime.in_hours(account.work_times.where(datetime: Date.today.beginning_of_week..Date.today.end_of_week).sum(:minutes)) %> / <%= WorkTime.in_hours(account.work_load_per_week) %>
          <br />
          <%= t("this_month") %>: <%= WorkTime.in_hours(account.work_times.where(datetime: Date.today.beginning_of_month..Date.today.end_of_month).sum(:minutes)) %> / <%= WorkTime.in_hours(account.work_load_per_week*(((Date.today.end_of_month - Date.today.beginning_of_month).to_f / 7).round(2))) %>
          <br />
          <%= t("this_year") %>: <%= WorkTime.in_hours(account.work_times.where(datetime: Date.today.beginning_of_year..Date.today.end_of_year).sum(:minutes)) %> / <%= WorkTime.in_hours(Account.calculate_work_load_in_duration(account.work_load_per_week, Date.today.beginning_of_year, Date.today.end_of_year)) %>
          <br />
          <%= t("altogether").capitalize %>: <%= WorkTime.in_hours(account.work_times.sum(:minutes)) %> / <%= WorkTime.in_hours(Account.calculate_work_load_in_duration(account.work_load_per_week, account.work_times.order(:datetime).first.datetime.to_date, account.work_times.order(:datetime).last.datetime.to_date)) unless account.work_times.empty? %>
        </p>
      </div>
      <div class="col-12 col-sm-6">
        <p class="card-text">
          <%= link_to Account.human_attribute_name("edit_account"), edit_account_path(account), class: "", data: { cy: "select_this_account" } %>
          <br />
          <%= link_to t("manage_categories"), manage_categories_account_path(account), data: { cy: "manage_categories" } %>
          <br />
          <%= link_to t("my_accounts"), my_accounts_accounts_path %>
        </p>
      </div>
    </div>

  </div>
</div>

app/views/accounts/_manage_categories.html.erb
<main class="container main_left">
  <h1><%= t("manage_categories") %></h1>
  <%= link_to t("back"), account_path(account), class: "secondary-button", data: { cy: "back" } %>

  <hr>

    <% account.categories.each do |category|  %>
      <div>
        <h2><%= category.name %></h2>
        <%= link_to t("edit"), edit_category_path(category), data: { cy: "edit_category" } %> | 
        <%= link_to t("delete"), category, method: :delete, data: { cy: "delete_category", confirm: 'Are you sure?' } %>
        <%= render "select_options/table", category: category %>
      </div>
      <hr>
    <% end %>

    <div class="standard-card ">
      <div class="card-body">
        <h5 class="card-title"><%= Category.human_attribute_name("add", category: Category.model_name.human) %></h5>
        <p class="card-text">
          <%= render 'categories/form', category: Category.new, account: account %>
        </p>
      </div>
    </div>

  <%= link_to t("back"), account_path(account), class: "secondary-button", data: { cy: "back" } %>

</main>

app/views/accounts/_my_accounts.html.erb
<div class="container">
  <h1><%= t("my_accounts") %></h1>
  <p class="lead">
    <%= t("please_select_account", account: Account.model_name.human) %>
  </p>
</div>

<div class="container mb-2">
  <div class="row row-cols-1 row-cols-md-3 g-3">
      <% user.accounts.each do |account| %>
      <div class="col">
        <div class="card mb-3 h-100">
            <%#= image_tag("account_placeholder.jpg", class: "img-fluid rounded-start") %>
          <div class="card-body">
            <h5 class="card-title"><%= account.name %></h5>
            <p class="card-text">
              <%= t("this_week") %>: <%= WorkTime.in_hours(account.work_times.where(datetime: Date.today.beginning_of_week..Date.today.end_of_week).sum(:minutes)) %>
              <br />
              <%= t("this_month") %>: <%= WorkTime.in_hours(account.work_times.where(datetime: Date.today.beginning_of_month..Date.today.end_of_month).sum(:minutes)) %>
              <br />
              <%= t("this_year") %>: <%= WorkTime.in_hours(account.work_times.where(datetime: Date.today.beginning_of_year..Date.today.end_of_year).sum(:minutes)) %>
              <br />
              <%= t("altogether").capitalize %>: <%= WorkTime.in_hours(account.work_times.sum(:minutes)) %>
            </p>
            <%= link_to t("select"), account_path(account), class: "primary-button", data: { cy: "select_account" } %>
            <%#= link_to Account.human_attribute_name("edit_account"), edit_account_path(account), class: "secondary-button", data: { cy: "select_this_account" } %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="col">
      <div class="card mb-3 h-100">
          <%#= image_tag("new_account_placeholder.jpg", class: "img-fluid rounded-start") %>
        <div class="card-body">
          <p class="card-text">
          <%= link_to Account.human_attribute_name("create_new_account"), new_account_path, class: "primary-button", data: { cy: "select_this_account" } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/_select_date_range.html.erb
    <p class="card-text">
      <button type="button" data-start_date="<%= Date.today.strftime("%d-%m-%Y") %>" data-end_date="<%= Date.today.strftime("%d-%m-%Y") %>" class="date_range_button set_date_range_button"><%= t("today") %></button>
      <button type="button" data-start_date="<%= Date.today.beginning_of_week.strftime("%d-%m-%Y") %>" data-end_date="<%= Date.today.end_of_week.strftime("%d-%m-%Y") %>" class="date_range_button set_date_range_button"><%= t("this_week") %></button>
      <button type="button" data-start_date="<%= Date.today.beginning_of_month.strftime("%d-%m-%Y") %>" data-end_date="<%= Date.today.end_of_month.strftime("%d-%m-%Y") %>" class="date_range_button set_date_range_button"><%= t("this_month") %></button>
      <button type="button" data-start_date="<%= Date.today.beginning_of_year.strftime("%d-%m-%Y") %>" data-end_date="<%= Date.today.end_of_year.strftime("%d-%m-%Y") %>" class="date_range_button set_date_range_button"><%= t("this_year") %></button>
      <button type="button" class="date_range_button set_date_range_button"><%= t("this_account") %></button>

      <button class="date_range_button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        <%= t("select_date_range") %>
      </button>
    </p>

    <div class="collapse" id="collapseExample">
      <div class="card card-body">
        <div class="row">
          <div class="col-6">
            <div class="input-group mb-3">
              <span class="input-group-text"><%= t("start_date") %></span>
              <input type="text" id="work_time_start_date" class="form-control" placeholder="StartDate">
            </div>
          </div>
          <div class="col-6">
            <div class="input-group mb-3">
              <span class="input-group-text"><%= t("end_date") %></span>
              <input type="text" id="work_time_end_date" class="form-control" placeholder="EndDate">
            </div>
          </div>
        </div>
        <button type="button" class="primary-button select_date_range_button"><%= t("apply_date_range") %></button>      </div>
    </div>


<script type="text/javascript">

  var spinner_html = `
  <div class="text-center my-4" style="height: 500px">
    <div class="spinner-grow" style="width: 3rem; height: 3rem;" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
`;

  $(document).ready(function() {

    $( ".select_date_range_button" ).click(function() {
      var work_time_start_date = $('#work_time_start_date').val();
      var work_time_end_date = $('#work_time_end_date').val();
      //window.location.replace("<%= account_path(account) %>" + "/" + $('#work_time_start_date').val() + "/" + $('#work_time_end_date').val());
      $(".data_overview").empty();
      $(".data_overview").html(spinner_html);

      $.ajax({
        url: "<%= data_overview_account_path(@account) %>",
        method: 'GET',
        data: {
          id: account.id,
          start_date: work_time_start_date,
          end_date: work_time_end_date
        }
      }).done(function( data ) {

        $(".data_overview").replaceWith(function() {
            return $(data).hide().fadeIn(1000);
        });

      });
    });

    $( ".set_date_range_button" ).click(function() {
      //window.location.replace("<%= account_path(account) %>" + "/" + $(this).data("start_date") + "/" + $(this).data("end_date"));

      $(".data_overview").empty();
      $(".data_overview").html(spinner_html);

      var data = {
        id: account.id,
        interval: "P1W",
      };

      if (typeof $(this).data("start_date") !== 'undefined') {
        data.start_date = $(this).data("start_date")
      }

      if (typeof $(this).data("end_date") !== 'undefined') {
        data.end_date = $(this).data("end_date")
      }

      $.ajax({
        url: "<%= data_overview_account_path(@account) %>",
        method: 'GET',
        data: data
      }).done(function( data ) {

        $(".data_overview").replaceWith(function() {
            return $(data).hide().fadeIn(1000);
        });

      });

    });


    $( function() {
      $("#work_time_start_date").datepicker({'language' : 'de', 'dateFormat' : 'dd-mm-yy', firstDay: 1 });
      $("#work_time_end_date").datepicker({'language' : 'de', 'dateFormat' : 'dd-mm-yy', firstDay: 1 });
      $("#work_time_start_date").datepicker( "setDate" , '<%= start_date.strftime("%d-%m-%Y") %>' );
      $("#work_time_end_date").datepicker( "setDate" , '<%= end_date.strftime("%d-%m-%Y") %>' );
    } );

  });

</script>

app/views/accounts/_show.html.erb
<div class="container">
  <%= render "accounts/information_card", account: account %>

  <div class="standard-card ">
    <div class="card-body">
      <h5 class="card-title"><%= WorkTime.human_attribute_name("enter_work_time", work_time: WorkTime.model_name.human) %></h5>
      <p class="card-text">
        <%= render 'work_times/form', work_time: WorkTime.new, account: account %>
      </p>
    </div>
  </div>

  <%= render "accounts/data_overview", account: account, start_date: start_date, end_date: end_date %>

</div>

app/views/accounts/data_overview.html.erb
<%= render 'accounts/data_overview', account: @account, start_date: @start_date, end_date: @end_date %>

app/views/accounts/edit.html.erb
<div class="container">
  <h1><%= Account.human_attribute_name("edit", account: Account.model_name.human) %></h1>
  <%= render 'form', account: @account %>
</div>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/manage_categories.html.erb
<div class="container">
  <%= render "accounts/manage_categories", account: @account %>
</div>

app/views/accounts/my_accounts.html.erb
<main class="main_left">
  <%= render 'accounts/my_accounts', user: current_user %>
</main>

app/views/accounts/new.html.erb
<div class="container">
  <h1><%= Account.human_attribute_name("add", account: Account.model_name.human) %></h1>
  <%= render 'form', account: @account %>
</div>

app/views/accounts/show.html.erb
<%= render 'show', account: @account, start_date: @start_date, end_date: @end_date %>